#!/usr/bin/env bash
# Tunnel laptop → Postgres on the DN Tech VPS (bound to localhost:5432 there).
# Credentials come from the VPS backend .env — never committed.
#
# Usage (from repo root or backend/):
#   ./scripts/db-vps.sh tunnel
#   ./scripts/db-vps.sh with npm run db:seed-products
#   ./scripts/db-vps.sh stop
#
# Env overrides:
#   SSH_HOST=dntech   LOCAL_PORT=5433   REMOTE_ENV=~/dntech/backend/.env

set -euo pipefail

SSH_HOST="${SSH_HOST:-dntech}"
LOCAL_PORT="${LOCAL_PORT:-5433}"
REMOTE_PG_HOST="${REMOTE_PG_HOST:-127.0.0.1}"
REMOTE_PG_PORT="${REMOTE_PG_PORT:-5432}"
PID_FILE="${TMPDIR:-/tmp}/dntech-vps-pg-${LOCAL_PORT}.pid"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
ENV_FILE="$BACKEND_DIR/.env.vps"

log() { printf '%s\n' "$*" >&2; }

die() {
  log "error: $*"
  exit 1
}

backend_cd() {
  cd "$BACKEND_DIR"
}

tunnel_running() {
  if [[ -f "$PID_FILE" ]]; then
    local pid
    pid="$(cat "$PID_FILE" 2>/dev/null || true)"
    if [[ -n "${pid:-}" ]] && kill -0 "$pid" 2>/dev/null; then
      return 0
    fi
  fi
  if command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$LOCAL_PORT" -sTCP:LISTEN >/dev/null 2>&1
    return $?
  fi
  return 1
}

wait_for_port() {
  local i
  for i in $(seq 1 25); do
    if command -v nc >/dev/null 2>&1; then
      nc -z 127.0.0.1 "$LOCAL_PORT" 2>/dev/null && return 0
    elif command -v lsof >/dev/null 2>&1; then
      lsof -iTCP:"$LOCAL_PORT" -sTCP:LISTEN >/dev/null 2>&1 && return 0
    fi
    sleep 0.2
  done
  die "tunnel did not listen on 127.0.0.1:${LOCAL_PORT}"
}

start_tunnel() {
  if tunnel_running; then
    log "tunnel already up on 127.0.0.1:${LOCAL_PORT}"
    return 0
  fi

  log "opening SSH tunnel ${SSH_HOST} → ${REMOTE_PG_HOST}:${REMOTE_PG_PORT} as 127.0.0.1:${LOCAL_PORT}"
  ssh -f -N \
    -o ExitOnForwardFailure=yes \
    -o ServerAliveInterval=30 \
    -L "${LOCAL_PORT}:${REMOTE_PG_HOST}:${REMOTE_PG_PORT}" \
    "$SSH_HOST"

  # ssh -f backgrounds; find the listener pid
  local pid
  pid="$(lsof -tiTCP:"$LOCAL_PORT" -sTCP:LISTEN 2>/dev/null | head -1 || true)"
  if [[ -z "${pid:-}" ]]; then
    wait_for_port
    pid="$(lsof -tiTCP:"$LOCAL_PORT" -sTCP:LISTEN 2>/dev/null | head -1 || true)"
  fi
  [[ -n "${pid:-}" ]] || die "could not find ssh tunnel pid"
  echo "$pid" >"$PID_FILE"
  wait_for_port
  log "tunnel pid ${pid}"
}

stop_tunnel() {
  local pid=""
  if [[ -f "$PID_FILE" ]]; then
    pid="$(cat "$PID_FILE" 2>/dev/null || true)"
  fi
  if [[ -n "${pid:-}" ]] && kill -0 "$pid" 2>/dev/null; then
    kill "$pid" 2>/dev/null || true
    log "stopped tunnel pid ${pid}"
  elif command -v lsof >/dev/null 2>&1; then
    local extra
    extra="$(lsof -tiTCP:"$LOCAL_PORT" -sTCP:LISTEN 2>/dev/null || true)"
    if [[ -n "${extra:-}" ]]; then
      # shellcheck disable=SC2086
      kill $extra 2>/dev/null || true
      log "stopped listener(s) on port ${LOCAL_PORT}"
    else
      log "no tunnel on port ${LOCAL_PORT}"
    fi
  else
    log "no tunnel pid file"
  fi
  rm -f "$PID_FILE"
}

fetch_remote_database_url() {
  ssh -o BatchMode=yes "$SSH_HOST" 'bash -s' <<'REMOTE'
set -euo pipefail
candidates=(
  "$HOME/dntech/backend/.env"
  "/var/www/dntech/backend/.env"
  "$HOME/backend/.env"
)
for f in "${candidates[@]}"; do
  if [[ -f "$f" ]]; then
    line="$(grep -E '^[[:space:]]*DATABASE_URL=' "$f" | tail -1 || true)"
    if [[ -n "${line:-}" ]]; then
      printf '%s\n' "$line"
      exit 0
    fi
  fi
done
echo "DATABASE_URL not found in VPS .env (tried ~/dntech/backend/.env, /var/www/dntech/backend/.env)" >&2
exit 1
REMOTE
}

strip_url() {
  local line="$1"
  line="${line#DATABASE_URL=}"
  line="${line#"${line%%[![:space:]]*}"}"
  if [[ "$line" == \"*\" ]]; then
    line="${line#\"}"
    line="${line%\"}"
  elif [[ "$line" == \'*\' ]]; then
    line="${line#\'}"
    line="${line%\'}"
  fi
  printf '%s' "$line"
}

rewrite_url_via_tunnel() {
  local url="$1" rewritten
  command -v python3 >/dev/null 2>&1 || die "python3 required to rewrite DATABASE_URL for the tunnel"
  rewritten="$(python3 "$SCRIPT_DIR/rewrite-pg-url.py" "$url" "$LOCAL_PORT")" || die "could not rewrite DATABASE_URL host"
  [[ -n "$rewritten" ]] || die "empty rewritten DATABASE_URL"
  printf '%s' "$rewritten"
}

write_env_vps() {
  local raw rewritten
  raw="$(fetch_remote_database_url)"
  raw="$(strip_url "$raw")"
  [[ -n "$raw" ]] || die "empty DATABASE_URL from VPS"
  rewritten="$(rewrite_url_via_tunnel "$raw")"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/db-vps.sh — do not commit. Points at VPS Postgres via SSH tunnel.
DATABASE_URL="${rewritten}"
EOF
  log "wrote ${ENV_FILE} (mode 600)"
}

load_vps_database_url() {
  [[ -f "$ENV_FILE" ]] || write_env_vps
  # shellcheck disable=SC1090
  DATABASE_URL="$(strip_url "$(grep -E '^[[:space:]]*DATABASE_URL=' "$ENV_FILE" | tail -1)")"
  export DATABASE_URL
  [[ -n "${DATABASE_URL:-}" ]] || die "DATABASE_URL missing in ${ENV_FILE}"
}

cmd_status() {
  if tunnel_running; then
    log "tunnel: up  127.0.0.1:${LOCAL_PORT}  (ssh ${SSH_HOST})"
  else
    log "tunnel: down"
    exit 1
  fi
}

is_admin_bootstrap_cmd() {
  local s="$*"
  # Exact `db:seed` (not db:seed-branding / db:seed-products / …)
  if [[ "$s" =~ (^|[[:space:]])db:seed([[:space:]]|$) ]]; then
    return 0
  fi
  if [[ "$s" == *prisma/seed.ts* ]]; then
    return 0
  fi
  return 1
}

cmd_with() {
  [[ $# -ge 1 ]] || die "usage: db-vps.sh with <command...>"
  if is_admin_bootstrap_cmd "$@"; then
    die "refusing admin bootstrap via 'with' (local NODE_ENV would rotate/create hashes). Use: npm run db:vps:seed"
  fi
  start_tunnel
  write_env_vps
  load_vps_database_url
  backend_cd
  log "using VPS Postgres via 127.0.0.1:${LOCAL_PORT}"
  exec "$@"
}

usage() {
  cat <<EOF
Use VPS Postgres from this laptop (SSH tunnel). Host alias: ${SSH_HOST}

  $(basename "$0") tunnel     start tunnel (stays up)
  $(basename "$0") stop       close tunnel
  $(basename "$0") status     check tunnel
  $(basename "$0") env        write backend/.env.vps from VPS DATABASE_URL
  $(basename "$0") with CMD   tunnel + env, then run CMD in backend/
                            e.g. $(basename "$0") with npm run db:seed-products
                            (refuses db:seed — use the seed subcommand)
  $(basename "$0") psql       psql through the tunnel
  $(basename "$0") push       prisma db push against VPS (needs CONFIRM_VPS_PUSH=1)
  $(basename "$0") seed       bootstrap admin + branding + products (VPS; rotates admin hash)

Postgres stays bound to localhost on the VPS. Do not open 5432 to the internet.
EOF
}

main() {
  local cmd="${1:-}"
  shift || true

  case "$cmd" in
    tunnel)
      start_tunnel
      write_env_vps
      log "or:      $(basename "$0") with npm run db:seed-products"
      ;;
    stop) stop_tunnel ;;
    status) cmd_status ;;
    env)
      start_tunnel
      write_env_vps
      ;;
    with) cmd_with "$@" ;;
    psql)
      start_tunnel
      write_env_vps
      load_vps_database_url
      exec psql "$DATABASE_URL"
      ;;
    push)
      [[ "${CONFIRM_VPS_PUSH:-}" == "1" ]] || die "refusing prisma db push to VPS. Re-run with CONFIRM_VPS_PUSH=1 if you intend to change production schema."
      start_tunnel
      write_env_vps
      load_vps_database_url
      backend_cd
      exec npx prisma db push
      ;;
    seed)
      [[ -n "${ADMIN_PASSWORD:-}" ]] || die "export ADMIN_PASSWORD in this shell first (min 12 chars; VPS seed refuses defaults)"
      export NODE_ENV=production
      export ROTATE_ADMIN=1
      start_tunnel
      write_env_vps
      load_vps_database_url
      backend_cd
      npm run db:seed
      npm run db:seed-branding
      npm run db:seed-products
      ;;
    -h|--help|help|"") usage ;;
    *) die "unknown command: ${cmd} (try help)" ;;
  esac
}

main "$@"
